use_frameworks!

def mobileCommonPods
 

 pod 'Alamofire', '~> 4.4'
 pod 'AlamofireImage'

end

target 'VSCWeatherForecast' do
     mobileCommonPods
end

target 'VSCWeatherForecastTests' do
     mobileCommonPods
end

target 'VSCWeather Widget' do
    mobileCommonPods
end

target 'weatherForecast Watch' do
    mobileCommonPods
end

target 'weatherForecast Watch Extension' do
    mobileCommonPods
end
